/**
 * External dependencies
 */
import React, { useEffect, useState } from 'react';
import { __ } from '@wordpress/i18n';
import { external } from '@wordpress/icons';
import { useGetSettings } from 'wcpay/data';

/**
 * Internal dependencies
 */
import {
	TextareaControl,
	Button,
	Icon,
} from 'wcpay/components/wp-components-wrapped';
import { generateCoverLetter } from './cover-letter-generator';
import type { ExtendedDispute } from './types';

interface CoverLetterProps {
	value: string;
	onChange: ( value: string, isManualEdit?: boolean ) => void;
	dispute: ExtendedDispute;
	bankName: string | null;
	readOnly?: boolean;
}

const CoverLetter: React.FC< CoverLetterProps > = ( {
	value,
	onChange,
	dispute,
	bankName,
	readOnly = false,
} ) => {
	const [ isAutoGenerating, setIsAutoGenerating ] = useState( true );
	const [ autoGeneratedContent ] = useState< string >( '' );
	const wcStoreCountry =
		wcSettings?.admin?.preloadSettings?.general
			?.woocommerce_default_country || ':';
	const [ storeCountry, storeState ] = wcStoreCountry.split( ':' );
	const [ accountDetails ] = useState( {
		name: wcSettings?.siteTitle || '<Your Business Name>',
		support_address_city:
			wcSettings?.admin?.preloadSettings?.general
				?.woocommerce_store_city || '',
		support_address_country: storeCountry,
		support_address_line1:
			wcSettings?.admin?.preloadSettings?.general
				?.woocommerce_store_address || '',
		support_address_line2:
			wcSettings?.admin?.preloadSettings?.general
				?.woocommerce_store_address_2 || '',
		support_address_postal_code:
			wcSettings?.admin?.preloadSettings?.general
				?.woocommerce_store_postcode || '',
		support_address_state: storeState,
	} );
	const settings = useGetSettings();

	useEffect( () => {
		if (
			! dispute ||
			! accountDetails ||
			Object.keys( accountDetails ).length === 0 ||
			! settings ||
			Object.keys( settings ).length === 0
		) {
			return;
		}

		// Generate content first to compare with loaded value
		const generatedContent = generateCoverLetter(
			dispute,
			accountDetails,
			settings,
			bankName
		);

		// If there's a value already set (from saved uncategorized_text), compare it with generated content
		if ( value ) {
			if ( value !== generatedContent ) {
				// Content differs from what would be auto-generated, mark as edited
				onChange( value, true );
			}
			return;
		}

		// No saved value, use generated content
		if ( isAutoGenerating ) {
			onChange( generatedContent, false );
		}
	}, [
		dispute,
		onChange,
		isAutoGenerating,
		value,
		autoGeneratedContent,
		bankName,
		accountDetails,
		settings,
	] );

	const handleViewCoverLetter = () => {
		const htmlContent = `
			<!DOCTYPE html>
			<html>
			<head>
				<meta charset="UTF-8">
				<title>${ __( 'Cover Letter', 'woocommerce-payments' ) }</title>
				<style>
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						line-height: 1.6;
						max-width: 120ch;
						margin: 40px auto;
						padding: 20px;
						text-align: justify;
					}
					pre {
						white-space: pre-wrap;
						word-wrap: break-word;
						word-break: break-word;
						overflow-wrap: break-word;
						max-width: 100%;
					}
					@media print {
						body {
							margin: 0;
							padding: 20px;
							font-size: 12px;
						}
						pre {
							font-size: 12px;
						}
						.no-print {
							display: none;
						}
					}
					.print-button-container {
						position: fixed;
						bottom: 20px;
						left: 50%;
						transform: translateX(-50%);
						background: white;
						padding: 10px;
						border-radius: 4px;
						box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
					}
					@media print {
						.print-button-container {
							display: none;
						}
					}
				</style>
			</head>
			<body>
				<pre>${ value }</pre>
				<div class="print-button-container no-print">
					<button onclick="window.print()" style="
						padding: 8px 16px;
						background: #3B5AFB;
						color: white;
						border: none;
						border-radius: 4px;
						cursor: pointer;
					">
						${ __( 'Print Cover Letter', 'woocommerce-payments' ) }
					</button>
				</div>
			</body>
			</html>
		`;

		const blob = new Blob( [ htmlContent ], { type: 'text/html' } );
		const url = URL.createObjectURL( blob );
		const printWindow = window.open( url, '_blank' );

		// Clean up the blob URL after the window loads
		if ( printWindow ) {
			printWindow.onload = () => {
				URL.revokeObjectURL( url );
			};
		}
	};

	const handleTextareaChange = ( newValue: string ) => {
		// If the value is empty, set the auto-generated content
		if ( newValue.trim() === '' ) {
			setIsAutoGenerating( true );
			onChange( autoGeneratedContent, false );
			return;
		}
		setIsAutoGenerating( false );
		onChange( newValue, newValue !== autoGeneratedContent );
	};

	return (
		<section className="wcpay-dispute-evidence-cover-letter">
			<TextareaControl
				label={ __( 'COVER LETTER', 'woocommerce-payments' ) }
				value={ value }
				onChange={ handleTextareaChange }
				rows={ 30 }
				className="wcpay-dispute-evidence-cover-letter__textarea"
				readOnly={ readOnly }
			/>
			<Button
				className="wcpay-dispute-evidence-cover-letter__print"
				variant="primary"
				onClick={ handleViewCoverLetter }
				icon={ <Icon icon={ external } size={ 24 } /> }
			>
				{ __( 'View cover letter', 'woocommerce-payments' ) }
			</Button>
		</section>
	);
};

export default CoverLetter;
