// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as StyleScss from "./style.scss";
import * as Components from "@woocommerce/components";

var List = {};

function _style(prim) {
  return StyleScss.style(prim);
}

function HorizontalList(Props) {
  var itemsOpt = Props.items;
  var items = itemsOpt !== undefined ? itemsOpt : [];
  return React.createElement(Components.List, {
              items: items,
              className: "woocommerce-list--horizontal"
            });
}

var make = HorizontalList;

var $$default = HorizontalList;

export {
  List ,
  _style ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
