version: 2
updates:
    # Enable version updates for npm
    - package-ecosystem: 'npm'
      # Look for `package.json` and `lock` files in the `root` directory
      directory: '/'
      # Check for updates once a week
      schedule:
        interval: 'weekly'
      ignore:
        # For @wordpress dependencies, ignore all updates as most of them need to be synced to the min WP version
        - dependency-name: "@wordpress/*"
        # For @woocommerce dependencies, ignore all updates as most of them need to be synced to the min WC version
        - dependency-name: "@woocommerce/*"
      # Reviewers for issues created
      reviewers:
        - 'Automattic/harmony'

    # Enable version updates for composer
    - package-ecosystem: 'composer'
      # Look for `package.json` and `lock` files in the `root` directory
      directory: '/'
      # Check for updates once a week
      schedule:
        interval: 'weekly'
      # Reviewers for issues created
      reviewers:
          - 'Automattic/harmony'

    # Enable version updates for Docker
    - package-ecosystem: 'docker'
      # Look for a `Dockerfile` in the `root` directory
      directory: '/'
      # Check for updates once a week
      schedule:
          interval: 'weekly'
      # Reviewers for issues created
      reviewers:
          - 'Automattic/harmony'
