language: php

# cache:
#   directories:
#     - vendor
#     - $HOME/.composer/cache

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0

# Additional tests against stable PHP (min recommended version is 5.6) and past supported versions of WP
# and code coverage report.
matrix:
  fast_finish: true
  include:
  - name: "Coding standard check"
   php: 7.2
   env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1
  - name: "PHP 7.3 unit tests"
    php: 7.3
    env: WP_VERSION=latest WP_MULTISITE=0
  - name: "PHP 7.3 unit tests using WordPress nightly"
    php: 7.3
    env: WP_VERSION=nightly WP_MULTISITE=0
  allow_failures:
  - php: 7.3
    env: WP_VERSION=latest WP_MULTISITE=0

before_script:
  - echo $HOME
  - echo $PWD
  - export PATH="$HOME/vendor/bin:$PATH"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=4.8.*|6.5.*"
  - phpunit --version
  - |
    # Run composer install only if we need it to run PHPCS
    if [[ ${RUN_PHPCS} == 1 ]]; then
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]] && [[ ${TRAVIS_PHP_VERSION:0:3} != "7.0" ]] ; then
      composer install
    fi
  - bash bin/install-wp-tests.sh woocommerce_test root '' localhost $WP_VERSION

script:
  - bash bin/phpunit.sh
  - bash bin/phpcs.sh
