networks:
  wcpay-network:
    external: true

volumes:
  ## Kludge for not having the ./docker directory bound recursively
  dockerdirectory:

services:
  wordpress:
    build:
      context: .
      dockerfile: ./docker/wordpress_xdebug/Dockerfile
      args:
        - XDEBUG_REMOTE_PORT=9000
        - XDEBUG_START_WITH_REQUEST=trigger
    container_name: wcpay_wp_${WORKTREE_ID:-default}
    image: wcpay_wp_${WORKTREE_ID:-default}
    restart: unless-stopped
    ports:
      - "${WP_PORT:-8082}:80"
    env_file:
      - default.env
    environment:
      WORDPRESS_DB_HOST: wcpay_db:3306
      WORDPRESS_CONFIG_EXTRA: |
        define('DOCKER_HOST', $$_SERVER['HTTP_X_FORWARDED_HOST'] ?? $$_SERVER['HTTP_X_ORIGINAL_HOST'] ?? $$_SERVER['HTTP_HOST'] ?? 'localhost');
        $$_SERVER['HTTP_HOST'] = DOCKER_HOST;
        define('DOCKER_REQUEST_URL', ( ! empty( $$_SERVER['HTTPS'] ) ? 'https://' : 'http://' ) . DOCKER_HOST);
        define('WP_SITEURL', DOCKER_REQUEST_URL);
        define('WP_HOME', DOCKER_REQUEST_URL);
    volumes:
      - ./docker/wordpress:/var/www/html/
      - ./docker/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./docker/logs/apache2/:/var/log/apache2
      - .:/var/www/html/wp-content/plugins/woocommerce-payments
      - ./docker/wc-payments-php.ini:/usr/local/etc/php/conf.d/wc-payments-php.ini
      - dockerdirectory:/var/www/html/wp-content/plugins/woocommerce-payments/docker
      - ./docker/bin:/var/scripts
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - wcpay-network
