networks:
  wcpay-network:
    name: wcpay-network

services:
  db:
    container_name: wcpay_db
    image: mariadb:10.5.8
    restart: unless-stopped
    ports:
      - "5678:3306"
    env_file:
      - default.env
    volumes:
      - ./docker/data:/var/lib/mysql
    networks:
      - wcpay-network

  phpmyadmin:
    container_name: wcpay_phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8083:80"
    env_file:
      - default.env
    depends_on:
      - db
    networks:
      - wcpay-network
