/**
 * External dependencies
 */
import React from 'react';
import { __, sprintf } from '@wordpress/i18n';
import interpolateComponents from '@automattic/interpolate-components';
import moment from 'moment';

/**
 * Internal dependencies
 */
import { getDepositMonthlyAnchorLabel } from 'wcpay/deposits/utils';
import type * as AccountOverview from 'wcpay/types/account-overview';

/**
 * The type of the props for the DepositScheduleDescription component.
 * Mimics the AccountOverview.Account['deposits_schedule'] declaration.
 */
type DepositsScheduleProps = AccountOverview.Account[ 'deposits_schedule' ];

/**
 * Renders the Deposit Schedule details component.
 *
 * eg "Your deposits are dispatched automatically every day"
 *
 * @param {DepositsScheduleProps} depositsSchedule The account's deposit schedule.
 * @return {JSX.Element} Rendered element with Deposit Schedule details.
 */
const DepositSchedule: React.FC< DepositsScheduleProps > = (
	depositsSchedule: DepositsScheduleProps
): JSX.Element => {
	// TODO: use the next deposits date generated by function in PR#7648.
	const nextDepositDate = 'January 1st, 2023';
	switch ( depositsSchedule.interval ) {
		case 'daily':
			return interpolateComponents( {
				mixedString: sprintf(
					/** translators: {{strong}}: placeholders are opening and closing strong tags. %s: is the date of the next deposit, e.g. "January 1st, 2023". */
					__(
						'Available funds are dispatched to your bank account {{strong}}automatically every day{{/strong}}, with your next scheduled deposit estimated for {{strong}}%s{{/strong}}.',
						'woocommerce-payments'
					),
					nextDepositDate
				),
				components: {
					strong: <strong />,
				},
			} );
		case 'weekly':
			const dayOfWeek = moment()
				.locale( 'en' )
				.day( depositsSchedule.weekly_anchor )
				.locale( moment.locale() )
				.format( 'dddd' );

			return interpolateComponents( {
				mixedString: sprintf(
					/** translators: %1$s: is the day of the week. eg "Friday". %2$s: is the date of the next deposit, e.g. "January 1st, 2023". {{strong}}: placeholders are opening and closing strong tags. */
					__(
						'Available funds are dispatched to your bank account {{strong}}automatically every %1$s{{/strong}}, with your next scheduled deposit estimated for {{strong}}%2$s{{/strong}}.',
						'woocommerce-payments'
					),
					dayOfWeek,
					nextDepositDate
				),
				components: {
					strong: <strong />,
				},
			} );
		case 'monthly':
			const monthlyAnchor = depositsSchedule.monthly_anchor;

			// If the monthly anchor is 31, it means the deposit is scheduled for the last day of the month and has special handling.
			if ( monthlyAnchor === 31 ) {
				return interpolateComponents( {
					mixedString: sprintf(
						/** translators: {{strong}}: placeholders are opening and closing strong tags. %s: is the date of the next deposit, e.g. "January 1st, 2023". */
						__(
							'Available funds are dispatched to your bank account {{strong}}automatically on the last day of every month{{/strong}}, with your next scheduled deposit estimated for {{strong}}%s{{/strong}}.',
							'woocommerce-payments'
						),
						nextDepositDate
					),
					components: {
						strong: <strong />,
					},
				} );
			}

			return interpolateComponents( {
				mixedString: sprintf(
					/** translators: {{strong}}: placeholders are opening and closing strong tags. %1$s: is the day of the month. eg "31st". %2$s: is the date of the next deposit, e.g. "January 1st, 2023". */
					__(
						'Available funds are dispatched to your bank account {{strong}}automatically on the %1$s of every month{{/strong}}, with your next scheduled deposit estimated for {{strong}}%2$s{{/strong}}.',
						'woocommerce-payments'
					),
					getDepositMonthlyAnchorLabel( {
						monthlyAnchor: monthlyAnchor,
						capitalize: false,
					} ),
					nextDepositDate
				),
				components: {
					strong: <strong />,
				},
			} );
		default:
			return <></>;
	}
};

export default DepositSchedule;
