name: Create a branch and a tag
description: Create a branch and a tag from the version provided

inputs:
  tag-name:
    description: "The tag name that the action should use to determine which branch and tag it should create (e.g. 4.5.0 or 4.5.0-test-2)"
    required: true
    
outputs: 
  branch-name:
    description: "The name of the branch created"
    value: ${{ steps.create_branch_tag.outputs.BRANCH_NAME }}
  tag-message:
    description: "The tagging message"
    value: ${{ steps.create_branch_tag.outputs.TAG_MESSAGE }}

runs:
  using: composite
  steps:
    - name: "Check the format of the tag"
      shell: bash
      env:
        TAG_NAME: ${{ inputs.tag-name }}
      run: |
        TAG_FORMAT=/^[0-9]\.[0-9]\.[0-9](-test-[1-3])*$/
        TRIMMED_TAG_NAME=$(echo "$TAG_NAME" | xargs)
        if ! [[ $TRIMMED_TAG_NAME =~ TAG_FORMAT ]]; then
          echo "::error::The tag name provided doesn't respect the format (tag name: $TAG_NAME)."
          exit 1
        fi
    - name: "Create a branch and tag"
      id: create_branch_tag
      shell: bash
      env:
        IS_PRERELEASE: ${{ contains( inputs.tag-name, 'test') }}
        TAG_NAME: ${{ inputs.tag-name }}
      run: |
        if ${{ env.IS_PRERELEASE }}; then
          echo "Created a test branch and tag." >> $GITHUB_STEP_SUMMARY
          BRANCH_NAME="testing/$TAG_NAME"
          TAG_MESSAGE="Version for testing $TAG_NAME. Not for Production"
        else
          echo ":rocket: Created a release branch and tag. :rocket:" >> $GITHUB_STEP_SUMMARY
          BRANCH_NAME="release/$TAG_NAME"
          TAG_MESSAGE="Version $TAG_NAME"
        fi

        git checkout -b $BRANCH_NAME
        git push origin $BRANCH_NAME
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
        
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git tag -a -m "$TAG_MESSAGE" $TAG_NAME
        git push origin $TAG_NAME
        echo "TAG_MESSAGE=$TAG_MESSAGE" >> $GITHUB_OUTPUT
