// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PaymentStatusChipGen from "./PaymentStatusChip.gen";
import * as Chip$WoocommercePayments from "../chip/chip.bs.js";

function __(prim, prim$1) {
  return PaymentStatusChipGen.__(prim, prim$1);
}

function getChipType(status) {
  if (typeof status === "number") {
    if (status >= 2) {
      if (status >= 5) {
        return /* Primary */0;
      } else {
        return /* Light */1;
      }
    } else {
      return /* Alert */3;
    }
  }
  var match = status._0;
  if (match !== 3 && match !== 0) {
    return /* Light */1;
  } else {
    return /* Primary */0;
  }
}

function getChipMessage(status) {
  if (typeof status === "number") {
    switch (status) {
      case /* Failed */0 :
          return PaymentStatusChipGen.__("Payment failed", "woocommerce-payments");
      case /* Blocked */1 :
          return PaymentStatusChipGen.__("Payment blocked", "woocommerce-payments");
      case /* PartiallyRefunded */2 :
          return PaymentStatusChipGen.__("Partial refund", "woocommerce-payments");
      case /* FullyRefunded */3 :
          return PaymentStatusChipGen.__("Refunded", "woocommerce-payments");
      case /* Paid */4 :
          return PaymentStatusChipGen.__("Paid", "woocommerce-payments");
      case /* Authorized */5 :
          return PaymentStatusChipGen.__("Payment authorized", "woocommerce-payments");
      
    }
  } else {
    switch (status._0) {
      case /* WarningNeedsResponse */0 :
          return PaymentStatusChipGen.__("Inquiry: Needs response", "woocommerce-payments");
      case /* WarningUnderReview */1 :
          return PaymentStatusChipGen.__("Inquiry: Under review", "woocommerce-payments");
      case /* WarningClosed */2 :
          return PaymentStatusChipGen.__("Inquiry: Closed", "woocommerce-payments");
      case /* NeedsResponse */3 :
          return PaymentStatusChipGen.__("Needs response", "woocommerce-payments");
      case /* UnderReview */4 :
          return PaymentStatusChipGen.__("Under review", "woocommerce-payments");
      case /* ChargeRefunded */5 :
          return PaymentStatusChipGen.__("Charge refunded", "woocommerce-payments");
      case /* Won */6 :
          return PaymentStatusChipGen.__("Won", "woocommerce-payments");
      case /* Lost */7 :
          return PaymentStatusChipGen.__("Lost", "woocommerce-payments");
      case /* NotDisputed */8 :
          return "";
      
    }
  }
}

function PaymentStatusChip(Props) {
  var status = Props.status;
  var chipType = getChipType(status);
  var message = getChipMessage(status);
  return React.createElement(Chip$WoocommercePayments.make, {
              message: message,
              chipType: chipType
            });
}

var make = PaymentStatusChip;

var $$default = PaymentStatusChip;

export {
  __ ,
  getChipType ,
  getChipMessage ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
