// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var PaymentStatusChipGen = require("./paymentStatusChip.gen");
var Chip$WoocommercePayments = require("../chip/chip.bs.js");
var Util$WoocommercePayments = require("../../utils/charge/util.bs.js");

function __(prim, prim$1) {
  return PaymentStatusChipGen.__(prim, prim$1);
}

function statusInfo(status) {
  if (status.TAG) {
    return {
            chipType: /* Light */1,
            message: ""
          };
  }
  switch (status._0) {
    case /* Failed */0 :
        return {
                chipType: /* Alert */3,
                message: PaymentStatusChipGen.__("Payment failed", "woocommerce-payments")
              };
    case /* Blocked */1 :
        return {
                chipType: /* Alert */3,
                message: PaymentStatusChipGen.__("Payment blocked", "woocommerce-payments")
              };
    case /* DisputeNeedsResponse */2 :
        return {
                chipType: /* Primary */0,
                message: PaymentStatusChipGen.__("Disputed: Needs response", "woocommerce-payments")
              };
    case /* DisputeUnderReview */3 :
        return {
                chipType: /* Light */1,
                message: PaymentStatusChipGen.__("Disputed: In review", "woocommerce-payments")
              };
    case /* DisputeWon */4 :
        return {
                chipType: /* Light */1,
                message: PaymentStatusChipGen.__("Disputed: Won", "woocommerce-payments")
              };
    case /* DisputeLost */5 :
        return {
                chipType: /* Light */1,
                message: PaymentStatusChipGen.__("Disputed: Lost", "woocommerce-payments")
              };
    case /* Disputed */6 :
        return {
                chipType: /* Light */1,
                message: ""
              };
    case /* PartiallyRefunded */7 :
        return {
                chipType: /* Light */1,
                message: PaymentStatusChipGen.__("Partial Refund", "woocommerce-payments")
              };
    case /* FullyRefunded */8 :
        return {
                chipType: /* Light */1,
                message: PaymentStatusChipGen.__("Refunded", "woocommerce-payments")
              };
    case /* Paid */9 :
        return {
                chipType: /* Light */1,
                message: PaymentStatusChipGen.__("Paid", "woocommerce-payments")
              };
    case /* Authorized */10 :
        return {
                chipType: /* Primary */0,
                message: PaymentStatusChipGen.__("Payment Authorized", "woocommerce-payments")
              };
    
  }
}

function PaymentStatusChip(Props) {
  var charge = Props.charge;
  var statusInfo$1 = statusInfo(Util$WoocommercePayments.getChargeStatus(charge));
  return React.createElement(Chip$WoocommercePayments.make, {
              message: statusInfo$1.message,
              chipType: statusInfo$1.chipType
            });
}

var make = PaymentStatusChip;

exports.__ = __;
exports.statusInfo = statusInfo;
exports.make = make;
/* react Not a pure module */
