// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Chip$WoocommercePayments = require("../chip/chip.bs.js");
var Util$WoocommercePayments = require("../../utils/charge/util.bs.js");

function statusInfo(status) {
  if (status.TAG) {
    return {
            chipType: "light",
            message: ""
          };
  }
  switch (status._0) {
    case /* Failed */0 :
        return {
                chipType: "alert",
                message: "Payment failed"
              };
    case /* Blocked */1 :
        return {
                chipType: "alert",
                message: "Payment blocked"
              };
    case /* DisputeNeedsResponse */2 :
        return {
                chipType: "primary",
                message: "Disputed: Needs response"
              };
    case /* DisputeUnderReview */3 :
        return {
                chipType: "light",
                message: "Disputed: In review"
              };
    case /* DisputeWon */4 :
        return {
                chipType: "light",
                message: "Disputed: Won"
              };
    case /* DisputeLost */5 :
        return {
                chipType: "light",
                message: "Disputed: Lost"
              };
    case /* Disputed */6 :
        return {
                chipType: "light",
                message: ""
              };
    case /* PartiallyRefunded */7 :
        return {
                chipType: "light",
                message: "Partial Refund"
              };
    case /* FullyRefunded */8 :
        return {
                chipType: "light",
                message: "Refunded"
              };
    case /* Paid */9 :
        return {
                chipType: "light",
                message: "Paid"
              };
    case /* Authorized */10 :
        return {
                chipType: "primary",
                message: "Payment Authorized"
              };
    
  }
}

function PaymentStatusChip(Props) {
  var charge = Props.charge;
  var statusInfo$1 = statusInfo(Util$WoocommercePayments.getChargeStatus(charge));
  return React.createElement(Chip$WoocommercePayments.make, {
              message: statusInfo$1.message,
              chipType: statusInfo$1.chipType
            });
}

var make = PaymentStatusChip;

exports.statusInfo = statusInfo;
exports.make = make;
/* react Not a pure module */
