// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function getComponent(placeholder, children, value, param) {
  if (placeholder !== undefined) {
    return Caml_option.valFromOption(placeholder);
  } else if (children !== undefined) {
    return Caml_option.valFromOption(children);
  } else if (value !== undefined) {
    return Caml_option.valFromOption(value);
  } else {
    return null;
  }
}

function getClass(display) {
  return "is-loadable-placeholder" + (
          "" === display ? "" : " is-" + display
        );
}

function Loadable(Props) {
  var isLoadingOpt = Props.isLoading;
  var displayOpt = Props.display;
  var placeholderOpt = Props.placeholder;
  var valueOpt = Props.value;
  var childrenOpt = Props.children;
  var isLoading = isLoadingOpt !== undefined ? isLoadingOpt : false;
  var display = displayOpt !== undefined ? displayOpt : "";
  var placeholder = placeholderOpt !== undefined ? Caml_option.valFromOption(placeholderOpt) : null;
  var value = valueOpt !== undefined ? Caml_option.valFromOption(valueOpt) : null;
  var children = childrenOpt !== undefined ? Caml_option.valFromOption(childrenOpt) : null;
  if (isLoading) {
    return React.createElement("span", {
                "aria-busy": true,
                className: getClass(display)
              }, getComponent(Caml_option.some(placeholder), Caml_option.some(children), Caml_option.some(value), undefined));
  } else {
    return getComponent(undefined, Caml_option.some(children), Caml_option.some(value), undefined);
  }
}

var make = Loadable;

var $$default = Loadable;

export {
  getComponent ,
  getClass ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
