// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Loadable$WoocommercePayments from "./loadable.bs.js";

function LoadableBlock(Props) {
  var numLinesOpt = Props.numLines;
  var isLoadingOpt = Props.isLoading;
  var valueOpt = Props.value;
  var childrenOpt = Props.children;
  var numLines = numLinesOpt !== undefined ? numLinesOpt : 1;
  var isLoading = isLoadingOpt !== undefined ? isLoadingOpt : false;
  var value = valueOpt !== undefined ? Caml_option.valFromOption(valueOpt) : null;
  var children = childrenOpt !== undefined ? Caml_option.valFromOption(childrenOpt) : null;
  var placeholder = React.createElement("p", {
        style: {
          lineHeight: String(numLines)
        }
      }, "Block placeholder");
  return React.createElement(Loadable$WoocommercePayments.make, {
              isLoading: isLoading,
              display: "block",
              placeholder: placeholder,
              value: value,
              children: children
            });
}

var make = LoadableBlock;

var $$default = LoadableBlock;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
