// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Loadable$WoocommercePayments = require("./loadable.bs.js");

function Loadable_block(Props) {
  var numLinesOpt = Props.numLines;
  var isLoading = Props.isLoading;
  var value = Props.value;
  var children = Props.children;
  var numLines = numLinesOpt !== undefined ? numLinesOpt : 1;
  var placeholder = Caml_option.some(React.createElement("p", {
            style: {
              lineHeight: String(numLines)
            }
          }, "Block placeholder"));
  return React.createElement(Loadable$WoocommercePayments.make, {
              isLoading: isLoading,
              display: "block",
              placeholder: placeholder,
              value: value,
              children: children
            });
}

var make = Loadable_block;

var $$default = Loadable_block;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
