<?php
namespace WCPay\Payment_Process\Exception;

use WCPay\Exceptions\Process_Payment_Exception;

class Existing_Processing_Order_Exception extends Process_Payment_Exception {
	/**
	 * Contains the redirect, generated by the payment.
	 *
	 * @var array
	 */
	protected $redirect;

	/**
	 * Sets the redirect array, used by gateways to
	 * redirect to the existing order's order received page.
	 *
	 * @param array $redirect The data, needed for redirect.
	 */
	public function set_redirect( array $redirect ) {
		$this->redirect = $redirect;
	}

	/**
	 * Returns the redirect array, used by gateways to
	 * redirect to the existing order's order received page.
	 *
	 * @return array
	 */
	public function get_redirect_array() {
		return $this->redirect;
	}
}
