// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");

var types = {
  hd: "primary",
  tl: {
    hd: "light",
    tl: {
      hd: "warning",
      tl: {
        hd: "alert",
        tl: /* [] */0
      }
    }
  }
};

function Chip$default(Props) {
  var message = Props.message;
  var chipType = Props.chipType;
  var isCompatOpt = Props.isCompat;
  var isCompat = isCompatOpt !== undefined ? isCompatOpt : false;
  var classNames = [
    "chip",
    "chip-" + (
      List.exists((function (t) {
              return chipType === t;
            }), types) ? chipType : "primary"
    ),
    isCompat ? "is-compat" : ""
  ];
  return React.createElement("span", {
              className: $$String.trim($$Array.fold_left((function (acc, curr) {
                          return acc + (" " + curr);
                        }), "", classNames))
            }, message);
}

var $$default = Chip$default;

exports.types = types;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
