// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");

function chipClass(chipType) {
  switch (chipType) {
    case /* Primary */0 :
        return "chip-primary";
    case /* Warning */2 :
        return "chip-warning";
    case /* Alert */3 :
        return "chip-alert";
    case /* Light */1 :
    case /* Default */4 :
        return "chip-light";
    
  }
}

function Chip(Props) {
  var message = Props.message;
  var chipTypeOpt = Props.chipType;
  var isCompatOpt = Props.isCompat;
  var chipType = chipTypeOpt !== undefined ? chipTypeOpt : /* Default */4;
  var isCompat = isCompatOpt !== undefined ? isCompatOpt : false;
  var classNames = [
    "chip",
    chipClass(chipType),
    isCompat ? "is-compat" : ""
  ];
  return React.createElement("span", {
              className: $$String.trim($$Array.fold_left((function (acc, curr) {
                          return acc + (" " + curr);
                        }), "", classNames))
            }, message);
}

var make = Chip;

exports.chipClass = chipClass;
exports.make = make;
/* react Not a pure module */
