name: "Process the changelog for WooCommerce Payments"
description: "Generate or amend the changelog entries"

inputs:
  release-version:
    description: "The release version for which the action should generate the changelog (e.g. 4.5.0)"
    required: true
  release-date:
    description: "The release date (format: YYYY-MM-DD) for which the action should generate the changelog (default: unreleased)"
    required: false
    default: "unreleased"
  action-type:
    description: 'Whether this is to generate or amend the changelog entries (generate or amend)'
    required: false
    default: "generate"
    
outputs: 
  changelog:
    description: "The escaped changelog content"
    value: ${{ steps.process_changelog.outputs.CHANGELOG }}

runs:
  using: composite
  steps:
    - name: "Process changelog for changelog.txt"
      id: process_changelog
      shell: bash
      env:
        ACTION_TYPE: ${{ inputs.action-type }}
        RELEASE_VERSION: ${{ inputs.release-version }}
        RELEASE_DATE: ${{ inputs.release-date }}
      run: |
        # Install this dev package globally to gather changelog entries while not including it into the release package
        composer global require automattic/jetpack-changelogger:^3.0.7
        
        if ${{ env.ACTION_TYPE == 'generate' }}; then
          CHANGELOG_FLAG=""
          echo "Generating the changelog entries." >> $GITHUB_STEP_SUMMARY
        else
          CHANGELOG_FLAG="--amend"
          echo "Amending the changelog entries." >> $GITHUB_STEP_SUMMARY
        fi
        
        ~/.composer/vendor/bin/changelogger write --use-version="$RELEASE_VERSION" --release-date="$RELEASE_DATE" $CHANGELOG_FLAG --no-interaction --yes
        
        echo "Picking up changelog for version '$RELEASE_VERSION'..."
        CHANGELOG=$(awk '/^= / { if (p) { exit }; p=1; next } p && NF' changelog.txt)
        echo "$CHANGELOG"
        
        # Escape backslash, new line and ampersand characters. The order is important.
        CHANGELOG=${CHANGELOG//\\/\\\\}
        CHANGELOG=${CHANGELOG//$'\n'/\\n} 
        CHANGELOG=${CHANGELOG//&/\\&}
        echo "CHANGELOG=$CHANGELOG" >> $GITHUB_OUTPUT

    - name: "Process changelog for readme.txt"
      shell: bash
      env:
        ACTION_TYPE: ${{ inputs.action-type }}
        RELEASE_VERSION: ${{ inputs.release-version }}
        RELEASE_DATE: ${{ inputs.release-date }}
        CHANGELOG: ${{ steps.process_changelog.outputs.CHANGELOG }}
      run: |
        if ${{ env.ACTION_TYPE == 'amend' }}; then
          perl -i -p0e "s/= $RELEASE_VERSION.*?(\n){2}//s" readme.txt # Delete the existing changelog for the release version first
        fi
        
        sed -ri "s|(== Changelog ==)|\1\n\n= $RELEASE_VERSION - $RELEASE_DATE =\n$CHANGELOG|" readme.txt
