<?php
/**
 * Class CountryFlags
 *
 * @package WooCommerce\Payments
 */

namespace WCPay\MultiCurrency;

use WCPay\Constants\Country_Codes;

defined( 'ABSPATH' ) || exit;

/**
 * Class that bring flags per country/currency.
 */
class CountryFlags {

	const EMOJI_COUNTRIES_FLAGS = [
		Country_Codes::ANDORRA                          => '🇦🇩',
		'AE'                                            => '🇦🇪',
		Country_Codes::AFGHANISTAN                      => '🇦🇫',
		Country_Codes::ANTIGUA_AND_BARBUDA              => '🇦🇬',
		'AI'                                            => '🇦🇮',
		Country_Codes::ALBANIA                          => '🇦🇱',
		Country_Codes::ARMENIA                          => '🇦🇲',
		Country_Codes::ANGOLA                           => '🇦🇴',
		'AQ'                                            => '🇦🇶',
		Country_Codes::ARGENTINA                        => '🇦🇷',
		'AS'                                            => '🇦🇸',
		Country_Codes::AUSTRIA                          => '🇦🇹',
		Country_Codes::AUSTRALIA                        => '🇦🇺',
		'AW'                                            => '🇦🇼',
		'AX'                                            => '🇦🇽',
		Country_Codes::AZERBAIJAN                       => '🇦🇿',
		Country_Codes::BOSNIA_AND_HERZEGOVINA           => '🇧🇦',
		Country_Codes::BARBADOS                         => '🇧🇧',
		Country_Codes::BANGLADESH                       => '🇧🇩',
		Country_Codes::BELGIUM                          => '🇧🇪',
		Country_Codes::BURKINA_FASO                     => '🇧🇫',
		Country_Codes::BULGARIA                         => '🇧🇬',
		Country_Codes::BAHRAIN                          => '🇧🇭',
		Country_Codes::BURUNDI                          => '🇧🇮',
		Country_Codes::BENIN                            => '🇧🇯',
		'BL'                                            => '🇧🇱',
		'BM'                                            => '🇧🇲',
		Country_Codes::BRUNEI                           => '🇧🇳',
		Country_Codes::BOLIVIA                          => '🇧🇴',
		'BQ'                                            => '🇧🇶',
		Country_Codes::BRAZIL                           => '🇧🇷',
		Country_Codes::BAHAMAS                          => '🇧🇸',
		Country_Codes::BHUTAN                           => '🇧🇹',
		'BV'                                            => '🇧🇻',
		Country_Codes::BOTSWANA                         => '🇧🇼',
		Country_Codes::BELARUS                          => '🇧🇾',
		Country_Codes::BELIZE                           => '🇧🇿',
		Country_Codes::CANADA                           => '🇨🇦',
		'CC'                                            => '🇨🇨',
		Country_Codes::DEMOCRATIC_REPUBLIC_OF_THE_CONGO => '🇨🇩',
		Country_Codes::CENTRAL_AFRICAN_REPUBLIC         => '🇨🇫',
		Country_Codes::CONGO                            => '🇨🇬',
		'CH'                                            => '🇨🇭',
		'CI'                                            => '🇨🇮',
		'CK'                                            => '🇨🇰',
		Country_Codes::CHILE                            => '🇨🇱',
		Country_Codes::CAMEROON                         => '🇨🇲',
		Country_Codes::CHINA                            => '🇨🇳',
		Country_Codes::COLOMBIA                         => '🇨🇴',
		Country_Codes::COSTA_RICA                       => '🇨🇷',
		Country_Codes::CUBA                             => '🇨🇺',
		Country_Codes::CABO_VERDE                       => '🇨🇻',
		'CW'                                            => '🇨🇼',
		'CX'                                            => '🇨🇽',
		Country_Codes::CYPRUS                           => '🇨🇾',
		Country_Codes::CZECHIA                          => '🇨🇿',
		Country_Codes::GERMANY                                            => '🇩🇪',
		Country_Codes::DJIBOUTI                         => '🇩🇯',
		Country_Codes::DENMARK                          => '🇩🇰',
		Country_Codes::DOMINICA                         => '🇩🇲',
		Country_Codes::DOMINICAN_REPUBLIC               => '🇩🇴',
		Country_Codes::ALGERIA                          => '🇩🇿',
		Country_Codes::ECUADOR                          => '🇪🇨',
		Country_Codes::ESTONIA                          => '🇪🇪',
		Country_Codes::EGYPT                            => '🇪🇬',
		'EH'                                            => '🇪🇭',
		Country_Codes::ERITREA                          => '🇪🇷',
		'ES'                                            => '🇪🇸',
		Country_Codes::ETHIOPIA                         => '🇪🇹',
		'EU'                                            => '🇪🇺',
		Country_Codes::FINLAND                          => '🇫🇮',
		Country_Codes::FIJI                             => '🇫🇯',
		'FK'                                            => '🇫🇰',
		'FM'                                            => '🇫🇲',
		'FO'                                            => '🇫🇴',
		Country_Codes::FRANCE                           => '🇫🇷',
		Country_Codes::GABON                                            => '🇬🇦',
		'GB'                                            => '🇬🇧',
		Country_Codes::GRENADA                                            => '🇬🇩',
		Country_Codes::GEORGIA                                            => '🇬🇪',
		'GF'                                            => '🇬🇫',
		'GG'                                            => '🇬🇬',
		Country_Codes::GHANA                                            => '🇬🇭',
		'GI'                                            => '🇬🇮',
		'GL'                                            => '🇬🇱',
		Country_Codes::GAMBIA                                            => '🇬🇲',
		Country_Codes::GUINEA                                            => '🇬🇳',
		'GP'                                            => '🇬🇵',
		Country_Codes::EQUATORIAL_GUINEA                => '🇬🇶',
		Country_Codes::GREECE                                            => '🇬🇷',
		'GS'                                            => '🇬🇸',
		Country_Codes::GUATEMALA                                            => '🇬🇹',
		'GU'                                            => '🇬🇺',
		Country_Codes::GUINEA_BISSAU                                            => '🇬🇼',
		Country_Codes::GUYANA                                            => '🇬🇾',
		'HK'                                            => '🇭🇰',
		'HM'                                            => '🇭🇲',
		Country_Codes::HONDURAS                                            => '🇭🇳',
		Country_Codes::CROATIA                          => '🇭🇷',
		Country_Codes::HAITI                                            => '🇭🇹',
		Country_Codes::HUNGARY                                            => '🇭🇺',
		'ID'                                            => '🇮🇩',
		'IE'                                            => '🇮🇪',
		'IL'                                            => '🇮🇱',
		'IM'                                            => '🇮🇲',
		'IN'                                            => '🇮🇳',
		'IO'                                            => '🇮🇴',
		'IQ'                                            => '🇮🇶',
		'IR'                                            => '🇮🇷',
		'IS'                                            => '🇮🇸',
		'IT'                                            => '🇮🇹',
		'JE'                                            => '🇯🇪',
		'JM'                                            => '🇯🇲',
		'JO'                                            => '🇯🇴',
		'JP'                                            => '🇯🇵',
		'KE'                                            => '🇰🇪',
		'KG'                                            => '🇰🇬',
		Country_Codes::CAMBODIA                         => '🇰🇭',
		'KI'                                            => '🇰🇮',
		Country_Codes::COMOROS                          => '🇰🇲',
		'KN'                                            => '🇰🇳',
		'KP'                                            => '🇰🇵',
		'KR'                                            => '🇰🇷',
		'KW'                                            => '🇰🇼',
		'KY'                                            => '🇰🇾',
		'KZ'                                            => '🇰🇿',
		'LA'                                            => '🇱🇦',
		'LB'                                            => '🇱🇧',
		'LC'                                            => '🇱🇨',
		'LI'                                            => '🇱🇮',
		'LK'                                            => '🇱🇰',
		'LR'                                            => '🇱🇷',
		'LS'                                            => '🇱🇸',
		'LT'                                            => '🇱🇹',
		'LU'                                            => '🇱🇺',
		'LV'                                            => '🇱🇻',
		'LY'                                            => '🇱🇾',
		'MA'                                            => '🇲🇦',
		'MC'                                            => '🇲🇨',
		'MD'                                            => '🇲🇩',
		'ME'                                            => '🇲🇪',
		'MF'                                            => '🇲🇫',
		'MG'                                            => '🇲🇬',
		'MH'                                            => '🇲🇭',
		'MK'                                            => '🇲🇰',
		'ML'                                            => '🇲🇱',
		'MM'                                            => '🇲🇲',
		'MN'                                            => '🇲🇳',
		'MO'                                            => '🇲🇴',
		'MP'                                            => '🇲🇵',
		'MQ'                                            => '🇲🇶',
		'MR'                                            => '🇲🇷',
		'MS'                                            => '🇲🇸',
		'MT'                                            => '🇲🇹',
		'MU'                                            => '🇲🇺',
		'MV'                                            => '🇲🇻',
		'MW'                                            => '🇲🇼',
		'MX'                                            => '🇲🇽',
		'MY'                                            => '🇲🇾',
		'MZ'                                            => '🇲🇿',
		'NA'                                            => '🇳🇦',
		'NC'                                            => '🇳🇨',
		'NE'                                            => '🇳🇪',
		'NF'                                            => '🇳🇫',
		'NG'                                            => '🇳🇬',
		'NI'                                            => '🇳🇮',
		'NL'                                            => '🇳🇱',
		'NO'                                            => '🇳🇴',
		'NP'                                            => '🇳🇵',
		'NR'                                            => '🇳🇷',
		'NU'                                            => '🇳🇺',
		'NZ'                                            => '🇳🇿',
		'OM'                                            => '🇴🇲',
		'PA'                                            => '🇵🇦',
		'PE'                                            => '🇵🇪',
		'PF'                                            => '🇵🇫',
		'PG'                                            => '🇵🇬',
		'PH'                                            => '🇵🇭',
		'PK'                                            => '🇵🇰',
		'PL'                                            => '🇵🇱',
		'PM'                                            => '🇵🇲',
		'PN'                                            => '🇵🇳',
		'PR'                                            => '🇵🇷',
		'PS'                                            => '🇵🇸',
		'PT'                                            => '🇵🇹',
		'PW'                                            => '🇵🇼',
		'PY'                                            => '🇵🇾',
		'QA'                                            => '🇶🇦',
		'RE'                                            => '🇷🇪',
		'RO'                                            => '🇷🇴',
		'RS'                                            => '🇷🇸',
		'RU'                                            => '🇷🇺',
		'RW'                                            => '🇷🇼',
		'SA'                                            => '🇸🇦',
		'SB'                                            => '🇸🇧',
		'SC'                                            => '🇸🇨',
		'SD'                                            => '🇸🇩',
		'SE'                                            => '🇸🇪',
		'SG'                                            => '🇸🇬',
		'SH'                                            => '🇸🇭',
		'SI'                                            => '🇸🇮',
		'SJ'                                            => '🇸🇯',
		'SK'                                            => '🇸🇰',
		'SL'                                            => '🇸🇱',
		'SM'                                            => '🇸🇲',
		'SN'                                            => '🇸🇳',
		'SO'                                            => '🇸🇴',
		'SR'                                            => '🇸🇷',
		'SS'                                            => '🇸🇸',
		'ST'                                            => '🇸🇹',
		Country_Codes::EL_SALVADOR                      => '🇸🇻',
		'SX'                                            => '🇸🇽',
		'SY'                                            => '🇸🇾',
		Country_Codes::ESWATINI                         => '🇸🇿',
		'TC'                                            => '🇹🇨',
		Country_Codes::CHAD                             => '🇹🇩',
		'TF'                                            => '🇹🇫',
		'TG'                                            => '🇹🇬',
		'TH'                                            => '🇹🇭',
		'TJ'                                            => '🇹🇯',
		'TK'                                            => '🇹🇰',
		Country_Codes::EAST_TIMOR                       => '🇹🇱',
		'TM'                                            => '🇹🇲',
		'TN'                                            => '🇹🇳',
		'TO'                                            => '🇹🇴',
		'TR'                                            => '🇹🇷',
		'TT'                                            => '🇹🇹',
		'TV'                                            => '🇹🇻',
		'TW'                                            => '🇹🇼',
		'TZ'                                            => '🇹🇿',
		'UA'                                            => '🇺🇦',
		'UG'                                            => '🇺🇬',
		'UM'                                            => '🇺🇲',
		'US'                                            => '🇺🇸',
		'UY'                                            => '🇺🇾',
		'UZ'                                            => '🇺🇿',
		'VA'                                            => '🇻🇦',
		'VC'                                            => '🇻🇨',
		'VE'                                            => '🇻🇪',
		'VG'                                            => '🇻🇬',
		'VI'                                            => '🇻🇮',
		'VN'                                            => '🇻🇳',
		'VU'                                            => '🇻🇺',
		'WF'                                            => '🇼🇫',
		'WS'                                            => '🇼🇸',
		'XK'                                            => '🇽🇰',
		'YE'                                            => '🇾🇪',
		'YT'                                            => '🇾🇹',
		'ZA'                                            => '🇿🇦',
		'ZM'                                            => '🇿🇲',
		'ZW'                                            => '🇿🇼',
	];

	/**
	 * Retrieves a flag by country code.
	 *
	 * @param string $country country alpha-2 code (ISO 3166) like US.
	 * @return string
	 */
	public static function get_by_country( string $country ): string {
		return self::EMOJI_COUNTRIES_FLAGS[ $country ] ?? '';
	}

	/**
	 * Retrieves a flag by currency code.
	 *
	 * @param string $currency currency code (ISO 4217) like USD.
	 * @return string
	 */
	public static function get_by_currency( string $currency ): string {
		$exceptions = [
			'ANG' => '',
			'BTC' => '',
			'XAF' => '',
			'XCD' => '',
			'XOF' => '',
			'XPF' => '',
		];

		$flag = $exceptions[ $currency ] ?? self::get_by_country( substr( $currency, 0, -1 ) );

		return $flag;
	}
}
