enum PAYMENT_METHOD_IDS {
	AFFIRM = 'affirm',
	AFTERPAY_CLEARPAY = 'afterpay_clearpay',
	AU_BECS_DEBIT = 'au_becs_debit',
	BANCONTACT = 'bancontact',
	CARD = 'card',
	CARD_PRESENT = 'card_present',
	EPS = 'eps',
	GIROPAY = 'giropay',
	IDEAL = 'ideal',
	LINK = 'link',
	P24 = 'p24',
	SEPA_DEBIT = 'sepa_debit',
	SOFORT = 'sofort',
}

export enum PAYMENT_METHOD_TITLES {
	ach_credit_transfer = 'ACH Credit Transfer',
	ach_debit = 'ACH Debit',
	acss_debit = 'ACSS Debit',
	affirm = 'Affirm',
	afterpay_clearpay = 'Afterpay',
	alipay = 'Alipay',
	amex = 'American Express',
	au_becs_debit = 'AU BECS Debit',
	bancontact = 'Bancontact',
	card = 'Card Payment',
	card_present = 'In-Person Card Payment',
	diners = 'Diners Club',
	discover = 'Discover',
	eps = 'EPS',
	giropay = 'giropay',
	ideal = 'iDEAL',
	jcb = 'JCB',
	klarna = 'Klarna',
	link = 'Link',
	mastercard = 'Mastercard',
	multibanco = 'Multibanco',
	p24 = 'P24',
	sepa_debit = 'SEPA Debit',
	sofort = 'SOFORT',
	stripe_account = 'Stripe Account',
	unionpay = 'Union Pay',
	visa = 'Visa',
	wechat = 'WeChat',
}

export default PAYMENT_METHOD_IDS;
