export const cartWithItemsMock = {
	needs_shipping: true,
	totals: {
		total_items: '2399',
		total_items_tax: '198',
		total_fees: '0',
		total_fees_tax: '0',
		total_discount: '0',
		total_discount_tax: '0',
		total_shipping: '1100',
		total_shipping_tax: '0',
		total_price: '3697',
		total_tax: '198',
		tax_lines: [
			{
				name: 'US-CA Tax rate',
				price: '198',
				rate: '8.25%',
			},
		],
		currency_code: 'USD',
		currency_symbol: '$',
		currency_minor_unit: 2,
	},
	shipping_rates: [
		{
			package_id: 0,
			name: 'Shipment 1',
			shipping_rates: [
				{
					meta_data: [],
					rate_id: 'flat_rate:1',
					name: 'Flat rate',
					description: '',
					price: '1100',
					taxes: '0',
					instance_id: 1,
					method_id: 'flat_rate',
					selected: true,
					currency_minor_unit: 2,
				},
				{
					meta_data: [],
					rate_id: 'flat_rate:5',
					name: 'Express shipping',
					description: '',
					price: '2200',
					taxes: '0',
					instance_id: 5,
					method_id: 'flat_rate',
					selected: false,
					currency_minor_unit: 2,
				},
			],
		},
	],
	items: [
		{
			key: 'aab3238922bcc25a6f606eb525ffdc56',
			id: 14,
			type: 'simple',
			quantity: 1,
			name: 'Beanie',
			sku: 'woo-beanie',
			images: [],
			variation: [],
			item_data: [],
			prices: {
				price: '2399',
				regular_price: '2399',
				sale_price: '2399',
				price_range: null,
				currency_code: 'USD',
				currency_minor_unit: 2,
			},
			totals: {
				line_subtotal: '2399',
				line_subtotal_tax: '198',
				line_total: '2399',
				line_total_tax: '198',
				currency_code: 'USD',
				currency_minor_unit: 2,
			},
		},
	],
};

export const cartWithItemsAndCouponMock = {
	items: [
		{
			key: 'aab3238922bcc25a6f606eb525ffdc56',
			id: 14,
			type: 'simple',
			quantity: 1,
			name: 'Beanie',
			sku: 'woo-beanie',
			images: [],
			variation: [],
			item_data: [],
			prices: {
				price: '2399',
				regular_price: '2399',
				sale_price: '2399',
				price_range: null,
				currency_code: 'USD',
				currency_symbol: '$',
				currency_minor_unit: 2,
				currency_decimal_separator: '.',
				currency_thousand_separator: ',',
				currency_prefix: '$',
				currency_suffix: '',
				raw_prices: {
					precision: 6,
					price: '23990000',
					regular_price: '23990000',
					sale_price: '23990000',
				},
			},
			totals: {
				line_subtotal: '2399',
				line_subtotal_tax: '120',
				line_total: '0',
				line_total_tax: '0',
				currency_code: 'USD',
				currency_symbol: '$',
				currency_minor_unit: 2,
				currency_decimal_separator: '.',
				currency_thousand_separator: ',',
				currency_prefix: '$',
				currency_suffix: '',
			},
		},
	],
	coupons: [
		{
			code: 'allfree',
			discount_type: 'percent',
			totals: {
				total_discount: '1200',
				total_discount_tax: '60',
				currency_code: 'USD',
				currency_symbol: '$',
				currency_minor_unit: 2,
				currency_decimal_separator: '.',
				currency_thousand_separator: ',',
				currency_prefix: '$',
				currency_suffix: '',
			},
		},
	],
	fees: [],
	totals: {
		total_items: '2399',
		total_items_tax: '120',
		total_fees: '0',
		total_fees_tax: '0',
		total_discount: '2399',
		total_discount_tax: '120',
		total_shipping: '0',
		total_shipping_tax: '0',
		total_price: '0',
		total_tax: '0',
		tax_lines: [],
		currency_code: 'USD',
		currency_symbol: '$',
		currency_minor_unit: 2,
		currency_decimal_separator: '.',
		currency_thousand_separator: ',',
		currency_prefix: '$',
		currency_suffix: '',
	},
	needs_payment: false,
	needs_shipping: true,
	has_calculated_shipping: true,
	shipping_rates: [
		{
			package_id: 0,
			shipping_rates: [
				{
					rate_id: 'free_shipping:9',
					name: 'Free shipping',
					description: '',
					delivery_time: '',
					price: '0',
					taxes: '0',
					instance_id: 9,
					method_id: 'free_shipping',
					meta_data: [
						{
							key: 'Items',
							value: 'Cap &times; 1',
						},
					],
					selected: true,
					currency_code: 'USD',
					currency_symbol: '$',
					currency_minor_unit: 2,
					currency_decimal_separator: '.',
					currency_thousand_separator: ',',
					currency_prefix: '$',
					currency_suffix: '',
				},
				{
					rate_id: 'flat_rate:2',
					name: 'Flat rate',
					description: '',
					delivery_time: '',
					price: '1170',
					taxes: '59',
					instance_id: 2,
					method_id: 'flat_rate',
					meta_data: [
						{
							key: 'Items',
							value: 'Cap &times; 1',
						},
					],
					selected: false,
					currency_code: 'USD',
					currency_symbol: '$',
					currency_minor_unit: 2,
					currency_decimal_separator: '.',
					currency_thousand_separator: ',',
					currency_prefix: '$',
					currency_suffix: '',
				},
			],
		},
	],
};
