// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as StyleScss from "./style.scss";

function _style(prim) {
  return StyleScss.style(prim);
}

function ShortPaymentMethod(Props) {
  var payment = Props.payment;
  return Belt_Option.getWithDefault(Belt_Option.map(payment.card, (function (card) {
                    return React.createElement("span", {
                                className: "payment-method-details"
                              }, React.createElement("span", {
                                    className: "payment-method__brand payment-method__brand--" + card.brand
                                  }), "\u0020••••\u0020", card.last4);
                  })), React.createElement("span", undefined, "&ndash;"));
}

var make = ShortPaymentMethod;

var $$default = ShortPaymentMethod;

export {
  _style ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
