#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Warn about the push and ask for confirmation
read -p "Are you sure you want to push? (y/n): " confirm
if [ "$confirm" != "y" ]; then
  echo "Push aborted."
  exit 1
fi
