name: 'Prepare repo and run Atomic E2E Tests'
description: 'Runs E2E tests with retry & upload logs and screenshots'

runs:
  using: "composite"
  steps:
    - name: "Set up repository"
      uses: ./.github/actions/setup-repo

    - name: "Install dependencies"
      shell: bash
      run: npm ci

    - name: "Set up E2E environment"
      shell: bash
      run: |
        mkdir screenshots

    - name: "Run tests, upload screenshots & logs"
      uses: ./.github/actions/e2e/run-log-tests
