name: Build on comment

on:
  pull_request:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'buildpls'
          reaction: rocket
          prefix_only: true
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
