name: "Build branch"

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-zip:
    name: "Build the zip file"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up repository"
        uses: ./.github/actions/setup-repo

      - name: "Build the plugin"
        id: build_plugin
        uses: ./.github/actions/build

      - name: "Unzip the file (prevents double zip issue)"
        run: |
          echo ":information_source: Unzipping to a folder to prevent double-zip issue ([known limitation](https://github.com/actions/upload-artifact#zipped-artifact-downloads)). Increase in artifact size is expected since we're uploading the folder." >> $GITHUB_STEP_SUMMARY
          unzip ${{ steps.build_plugin.outputs.release-filename }} -d zipfile

      - name: "Upload the zip file as an artifact"
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "woocommerce-payments-${{ github.ref_name }}"
          path: zipfile
          retention-days: 7
