name: Check changelog

on:
  pull_request:
    branches:
      - develop
      - 'release/**'
jobs:
  check-changelog:
    name:    Check changelog
    runs-on: ubuntu-20.04
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      # enable dependencies caching
      - uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools:    composer
          coverage: none
      # Check if any changelog file is added when comparing the current branch vs the target branch.
      - run: bash bin/check-changelog.sh origin/"$GITHUB_BASE_REF" HEAD
