name: Check changelog

on:
  pull_request:
    branches:
      - develop
      - 'release/**'
jobs:
  check-changelog:
    name:    Check changelog
    runs-on: ubuntu-20.04
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      # enable dependencies caching
      - name: Add composer to cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools:    composer
          coverage: none
      # Install composer packages.
      - run: composer self-update 2.0.6 && composer install --no-progress
      # Fetch the target branch before running the check.
      - name: Fetch the target origin branch
        run: git fetch origin $GITHUB_BASE_REF
      # Check if any changelog file is added when comparing the current branch vs the target branch.
      - name: Check changelog
        run: bash bin/check-changelog.sh origin/$GITHUB_BASE_REF HEAD
