name: Code coverage

on:
  pull_request

jobs:
  woocommerce-coverage:
    name:    Code coverage
    runs-on: ubuntu-18.04
    strategy:
      fail-fast:    false
      max-parallel: 10
      matrix:
        woocommerce: [ '5.9.0' ]
        wordpress:   [ 'latest' ]
        php:         [ '7.4' ]
    env:
      WP_VERSION: ${{ matrix.wordpress }}
      WC_VERSION: ${{ matrix.woocommerce }}
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      # enable dependencies caching
      - uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools:       composer
          coverage:    xdebug2
      # run CI checks
      - run: if [[ "${{ matrix.php }}" == '7.0' ]]; then wget https://phar.phpunit.de/phpunit-6.5.14.phar && mv phpunit-6.5.14.phar phpunit.phar; fi;
      - run: bash bin/run-ci-tests-check-coverage.bash
