name: E2E Playwright Tests - Pull Request

on:
    pull_request:
        branches:
            - develop
            - trunk
            - 'try/playwright*' # Temporarily run tests on try branches
    workflow_dispatch:
    workflow_call:
        inputs:
            wcpay-use-build-artifact:
                type: boolean
                required: false
                default: false
            repo-branch:
                type: string
                required: false
                description: 'Branch to be used for running tests'

env:
    E2E_GH_TOKEN: ${{ secrets.E2E_GH_TOKEN }}
    WCP_DEV_TOOLS_REPO: ${{ secrets.WCP_DEV_TOOLS_REPO }}
    WCP_DEV_TOOLS_BRANCH: 'trunk'
    WCP_SERVER_REPO: ${{ secrets.WCP_SERVER_REPO }}
    WC_SUBSCRIPTIONS_REPO: ${{ secrets.WC_SUBSCRIPTIONS_REPO }}
    E2E_BLOG_ID: ${{ secrets.E2E_BLOG_ID }}
    E2E_BLOG_TOKEN: ${{ secrets.E2E_BLOG_TOKEN }}
    E2E_USER_TOKEN: ${{ secrets.E2E_USER_TOKEN }}
    WC_E2E_SCREENSHOTS: 1
    E2E_SLACK_CHANNEL: ${{ secrets.E2E_SLACK_CHANNEL }}
    E2E_SLACK_TOKEN: ${{ secrets.E2E_SLACK_TOKEN }}
    E2E_USE_LOCAL_SERVER: false
    E2E_RESULT_FILEPATH: 'tests/e2e/results.json'
    WCPAY_USE_BUILD_ARTIFACT: ${{ inputs.wcpay-use-build-artifact }}
    WCPAY_ARTIFACT_DIRECTORY: 'zipfile'
    NODE_ENV: 'test'
    FORCE_E2E_DEPS_SETUP: true

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    wcpay-e2e-tests:
        runs-on: ubuntu-latest

        name: WC - latest

        env:
            E2E_WP_VERSION: 'latest'
            E2E_WC_VERSION: 'latest'

        steps:
            - name: Checkout WCPay repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.repo-branch || github.ref }}

            - name: 'Download WooCommerce Payments build file'
              if: ${{ inputs.wcpay-use-build-artifact }}
              uses: actions/download-artifact@v4
              with:
                  name: woocommerce-payments
                  path: ${{ env.WCPAY_ARTIFACT_DIRECTORY }}

            - name: Setup E2E environment
              uses: ./.github/actions/e2e/env-setup

            - name: Install Playwright
              shell: bash
              run: |
                  echo "::group::Install Playwright"
                  npx playwright install chromium
                  echo "::endgroup::"

            - name: Run tests, upload screenshots & logs
              uses: ./.github/actions/e2e-pw/run-log-tests
