# This is a basic workflow to help you get started with Actions

name: WooCommerce Platform Checkout Test Site Auto-Sync

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the develop branch.
  push:
    branches: [ poc/sftp-autosync ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-upload"
  build-and-upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/poc/sftp-autosync@v2
      
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm install
          npm run build
          unzip woocommerce-payments.zip
      
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.TEST_SITE_FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.TEST_SITE_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.TEST_SITE_FTP_PASS }}
          LOCAL_DIR: woocommerce-payments/
          server-dir: /htdocs/wp-content/plugins
          METHOD: sftp
          PORT: 22
          ARGS: --delete
