name: PHP linting and tests

on:
  pull_request

env:
  WP_VERSION: latest
  WC_VERSION: 4.5.0  # the most used version here

jobs:
  lint:
    name:    PHP linting
    runs-on: ubuntu-16.04
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      - uses: ./.github/actions/php-setup
        with:
          php-version: '7.1'
      # install dependencies and run linter
      - run: composer self-update 2.0.6 && composer install --no-progress && ./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep .php$)

  test:
    name:    PHP testing
    runs-on: ubuntu-16.04
    strategy:
      fail-fast:    false
      max-parallel: 10
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4' ]
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      - uses: ./.github/actions/php-setup
        with:
          php-version: ${{ matrix.php }}
      # run CI checks
      - run: bash bin/run-ci-tests.bash
