name: PHP linting and tests

on:
  pull_request:
    branches:
      - master

env:
  WP_VERSION: latest
  WC_VERSION: 4.5.0  # the most used version here

jobs:
  lint:
    name:    PHP linting
    runs-on: ubuntu-16.04
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      # enable dependencies caching
      - uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          tools:       composer
          coverage:    none
      # install dependencies and run linter
      - run: composer self-update 2.0.6 && composer install --no-progress
      - run: ./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep .php$)

  test:
    name:    PHP testing
    runs-on: ubuntu-16.04
    strategy:
      fail-fast:    false
      max-parallel: 5
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0']
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      # enable dependencies caching
      - uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools:       composer
          extensions:  mysql
          coverage:    none
      # install dependencies and run tests
      - run: composer self-update 2.0.6 && composer install --no-progress
      - run: sudo systemctl start mysql.service
      - run: WCPAY_DIR="$GITHUB_WORKSPACE" bash ./bin/install-wp-tests.sh woocommerce_test root root localhost $WP_VERSION $WC_VERSION false
      - run: bash ./bin/phpunit.sh
