name: PHP linting and tests

on:
  pull_request

env:
<<<<<<< HEAD
  WP_VERSION: latest
  WC_VERSION: 5.6.0  # the min supported version as per L-2 policy
=======
  WP_VERSION:        latest
  WC_VERSION:        5.5.0  # the min supported version as per L-2 policy
  GUTENBERG_VERSION: latest
>>>>>>> 850ad8da563446b36524ad3f8f8b06b2a17f7cf1

jobs:
  lint:
    name:    PHP linting
    runs-on: ubuntu-18.04
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      # enable dependencies caching
      - uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
          tools:       composer
          coverage:    none
      # install dependencies and run linter
      - run: composer self-update 2.0.6 && composer install --no-progress && ./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep .php$) && ./vendor/bin/psalm

  test:
    name:    PHP testing
    runs-on: ubuntu-18.04
    strategy:
      fail-fast:    false
      max-parallel: 10
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4' ]
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      # enable dependencies caching
      - uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools:       composer
          coverage:    xdebug2
      # run CI checks
      - run: bash bin/run-ci-tests.bash
