name: PHP linting and tests

on:
  pull_request:
  merge_group:

env:
  WP_VERSION:        latest
  WC_L2_VERSION: '7.1.1'  # the min supported version as per L-2 policy
  GUTENBERG_VERSION: latest

jobs:
  lint:
    name:    PHP linting
    runs-on: ubuntu-20.04
    steps:
      # clone the repository
      - uses: actions/checkout@v3
      # enable dependencies caching
      - uses: actions/cache@v3
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          tools:       composer
          coverage:    none
      # install dependencies and run linter
      - run: composer self-update 2.0.6 && composer install --no-progress && ./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep .php$) && ./vendor/bin/psalm

  test:
    name:    PHP testing
    runs-on: ubuntu-20.04
    strategy:
      fail-fast:    false
      max-parallel: 10
      matrix:
        php: [ '7.2', '7.3', '7.4' ]
    steps:
      # clone the repository
      - uses: actions/checkout@v3
      # enable dependencies caching
      - uses: actions/cache@v3
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools:       composer
          coverage:    xdebug2
      # run CI checks
      - run: bash bin/run-ci-tests.bash
        env:
          WC_VERSION: ${{ env.WC_L2_VERSION }}
