name: PHP Compatibility

on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Check for version-specific PHP compatibility
  php-compatibility:
    name: PHP Compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: "Set up PHP"
        uses: ./.github/actions/setup-php
      - run: bash bin/phpcs-compat.sh
