name: "Handle post-release steps"

# This action will run when it is triggered manually
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The release version (e.g. 4.5.0)'
        required: true
        type: string
      allowMerge:
        description: 'Whether we allow merging trunk back into develop'
        required: false
        type: string
        default: "false"

defaults:
  run:
    shell: bash

jobs:
  update-wiki:
    name: "Update the wiki for the next release"
    runs-on: ubuntu-20.04
    env:
      RELEASE_VERSION: ${{ inputs.releaseVersion }}
    
    steps:
      - name: "Checkout repository (develop)"
        uses: actions/checkout@v3
        with:
          ref: 'develop'

      - name: "Get the next version"
        id: next_version
        run: |
          echo "NEXT_VERSION=5.1.0" >> $GITHUB_OUTPUT      

      - name: "Checkout repository's wiki (develop)"
        uses: actions/checkout@v3
        with:
          repository: "${{ github.repository }}.wiki"
          path: "wiki"

      - name: "Add new pages for the next release"
        env:
          NEXT_VERSION: ${{ steps.next_version.outputs.NEXT_VERSION }}
        run: |
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          
          NEXT_VERSION_INSTRUCTIONS_FILENAME="Release-testing-instructions-for-WC-Payments-$NEXT_VERSION"
          
          # If file doesn't exist yet
          if [ ! -e "$NEXT_VERSION_INSTRUCTIONS_FILENAME.md" ]; then
            touch "$NEXT_VERSION_INSTRUCTIONS_FILENAME.md"
            echo '{Replace with testing instructions}' > "$NEXT_VERSION_INSTRUCTIONS_FILENAME.md"
            echo "Created file \""$NEXT_VERSION_INSTRUCTIONS_FILENAME.md"\"." >> $GITHUB_STEP_SUMMARY
          else
              echo ":warning: File "$NEXT_VERSION_INSTRUCTIONS_FILENAME.md" already exists. No action needed." >> $GITHUB_STEP_SUMMARY
          fi
          
          # If an entry for the next version doesn't exist yet
          if ! grep -q "v$NEXT_VERSION" Release-testing-instructions.md; then
            echo -ne "\n* [v$NEXT_VERSION](https://github.com/Automattic/woocommerce-payments/wiki/$NEXT_VERSION_INSTRUCTIONS_FILENAME)" >> Release-testing-instructions.md
            echo "Added a new entry for v$NEXT_VERSION in \"Release-testing-instructions.md\"." >> $GITHUB_STEP_SUMMARY
          else
              echo ":warning: Entry for v$NEXT_VERSION already exists in \"Release-testing-instructions.md\". No action needed." >> $GITHUB_STEP_SUMMARY
          fi
          
          git commit -am "Update wiki for release $NEXT_VERSION"
          git push --set-upstream origin $BRANCH_NAME
