---
name: (pre-release) Weekly i18n tag
on:
  push:
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch: []

jobs:
  weekly-18n-tag:
    name: Push i18n pre-release tag
    runs-on: ubuntu-20.04

    steps:
      # clone the repository
      - uses: actions/checkout@v2
        with:
          ref: 'develop'

      - name: Push pre-release-tag
        run: |
          TAG="i18n-$(date +%Y%m%d)-test"
          MESSAGE="Version for internationalization testing $TAG. Not for production."
          REF=$(git rev-parse HEAD)

          echo "Pushing tag '$TAG' marking commit $REF to repository..."
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/git/tags \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data "{ \"tag\": \"$TAG\", \"message\": \"$MESSAGE\", \"type\": \"commit\", \"object\": \"$REF\" }" \
            --fail
