---
#
# NOTE: This workflow uses Deploy Key to publish a new tag
# to overcome GitHub design limitation that actions done with action token
# cannot trigger other workflows.
#
name: (pre-release) Weekly i18n tag
on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch: []

jobs:
  weekly-18n-tag:
    name: Push i18n pre-release tag
    runs-on: ubuntu-20.04

    steps:
      # clone the repository
      - uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
          # for testing
          ref: 'feature/1118-split-translations-workflow'
          # ref: 'develop'
      - name: Set GitHub actions as commit author
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create annotated tag
        id: create_tag_object
        run: |
          TAG="i18n-$(date +%Y%m%d)-test"
          MESSAGE="Version for internationalization testing $TAG. Not for production."
          REF=$(git rev-parse HEAD)

          git tag -a -m "$MESSAGE" $TAG
          git push origin $TAG
