---
name: (pre-release) Publish on tag push
on:
  push:
    tags:
      # ignore pure SemVer tags processed by release tool
      - '![0-9]+.[0-9]+.[0-9]+'
      # run for all other tags
      - '**'

jobs:
  i18n-release:
    name: Publish pre-release
    runs-on: ubuntu-20.04

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          exit 1
