---
name: (pre-release) Weekly i18n tag
on:
  push:
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch: []

jobs:
  weekly-18n-tag:
    name: Push i18n pre-release tag
    runs-on: ubuntu-20.04

    steps:
      # clone the repository
      - uses: actions/checkout@v2
        with:
          # for testing
          ref: 'feature/1118-split-translations-workflow'
          # ref: 'develop'

      - name: Create tag object
        id: create_tag_object
        run: |
          TAG="i18n-$(date +%Y%m%d)-test-$RANDOM"
          MESSAGE="Version for internationalization testing $TAG. Not for production."
          REF=$(git rev-parse HEAD)

          echo "Pushing tag object '$TAG' marking commit $REF to repository..."
          echo ::set-output name=RAW_TAG_OBJECT::$( curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/git/tags \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data "{ \"tag\": \"$TAG\", \"message\": \"$MESSAGE\", \"type\": \"commit\", \"object\": \"$REF\" }" \
            --fail
            )
          echo ::set-output name=TAG::$TAG

      - name: Create tag reference
        id: create_tag_reference
        env:
          TAG_OBJECT_SHA: ${{ fromJson( steps.create_tag_object.outputs.RAW_TAG_OBJECT ).sha }}
          TAG: ${{ steps.create_tag_object.outputs.TAG }}
        run: |
          echo "Creating tag reference /refs/tags/$TAG pointing to tag object $TAG_OBJECT_SHA..."
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/git/refs \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data "{\"ref\": \"refs/tags/$TAG\", \"sha\": \"$TAG_OBJECT_SHA\"}" \
            --fail
