---
name: (pre-release) Publish on tag push
on:
  push:
    tags:
      # ignore pure SemVer tags processed by release tool
      - '![0-9]+.[0-9]+.[0-9]+'
      # ignore 'i18n-...' weekly tags handled by another workflow
      - '!i18n-[0-9]+'
      # run for all other tags
      - '**'
env:
  RELEASE_FILENAME: 'woocommerce-payments.zip'

jobs:
  publish-pre-release:
    name: Publish pre-release
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:
      # clone the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the tag name
        id: get_tag
        run: echo ::set-output name=TAG_REF::${GITHUB_REF#refs/tags/}

      - name: Retrive tag information
        id: get_tag_info
        env:
          GITHUB_TAG_URL: ${{ format( 'https://api.github.com/repos/{0}/git/refs/tags/tag-{1}', github.repository, steps.get_tag.outputs.TAG_REF) }}
        run: |
          CURL_RESPONSE=$(curl --request GET \
              --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
              --url "$GITHUB_TAG_URL" \
              --silent \
              --output - \
              --write-out "\n%{http_code}\n" )
          HTTP_CODE=$(echo "$CURL_RESPONSE" | tail -n 1)
          CURL_RESPONSE=$(echo "$CURL_RESPONSE" | head -n -1)

          if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
            echo "::error::Could not retrieve tag information from GitHub:"
            echo "::error::$CURL_RESPONSE" >&2
            exit 1
          fi
          echo "::set-output name=RAW_TAG_DATA::$CURL_RESPONSE"

      - name: Retrive tag object
        id: get_tag_object
        env:
          TAG_OBJECT_URL: ${{ fromJson( steps.get_tag_info.outputs.RAW_TAG_DATA ).object.url }}
        run: echo ::set-output name=RAW_TAG_OBJECT::$(curl "$TAG_OBJECT_URL" )

      - name: Enable composer dependencies caching
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Enable npm dependencies caching
        uses: actions/cache@v2
        with:
          path: ~/.npm/
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
          coverage: none

      - name: Build release
        shell: bash
        run: |
          npm ci
          npm run build

          if [[ ! -f $RELEASE_FILENAME ]]; then
            echo "Failed to create release archive $RELEASE_FILENAME"
            exit 1
          fi

      - name: Extract changelog
        env:
          TAG: ${{ steps.get_tag.outputs.TAG_REF }}
        id: get_changelog
        shell: bash
        run: |
          # pick anything before the first dash as a version number
          VERSION=$(sed -E 's/^([^-]+)-.*/\1/' <<< $TAG)

          echo "Picking up changelog for version '$VERSION'..."
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]];
          then
            # Tag starts with SemVer, pick changelog for this version
            CHANGELOG=$(awk -v ver="$VERSION" '/^= / { if (p) { exit }; if ($2 == ver) { p=1; next } } p && NF' changelog.txt)
          else
            # Otherwise use the first changelog section
            CHANGELOG=$(awk '/^= / { if (p) { exit }; p=1; next } p && NF' changelog.txt)
          fi
          echo "$CHANGELOG"
          echo ::set-output name=CHANGELOG_JSON::$(echo "$CHANGELOG" | jq -aRs '.')

      - name: Create release
        id: create_release
        shell: bash
        env:
          TAG: ${{ steps.get_tag.outputs.TAG_REF }}
          TAG_MESSAGE: ${{ fromJson( steps.get_tag_object.outputs.RAW_TAG_OBJECT ).message }}
          CHANGELOG: ${{ steps.get_changelog.outputs.CHANGELOG_JSON }}
        run: |
          NAME=$( echo -n ${TAG_MESSAGE:=$TAG} | jq -aRs '.' )
          echo "Will build a release for tag '$TAG' with the name '$NAME'..."

          echo "Creating pre-release..."
          CURL_RESPONSE=$(curl --request POST \
              --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
              --header 'Content-Type: application/json' \
              --data "{\"tag_name\":\"$TAG\",\"target_commitish\":\"develop\",\"name\":$NAME,\"body\":$CHANGELOG,\"prerelease\":true}" \
              --silent \
              --fail \
              --url "https://api.github.com/repos/${{ github.repository }}/releases")

          if [ $? -ne 0 ]; then
            echo "Could not create release:"
            echo "$CURL_RESPONSE"
            exit 1
          fi

          echo "Release created."
          echo ::set-output name=RELEASE_JSON::$CURL_RESPONSE

      - name: Upload release assets
        id: upload_release_assets
        env:
          UPLOAD_URL: ${{ fromJson( steps.create_release.outputs.RELEASE_JSON ).upload_url }}
        shell: bash
        run: |
          echo "Uploading release assets to GitHub release..."

          # remove trailing attributes from upload_url
          upload_url=$(echo $UPLOAD_URL | sed -E 's/([^{]*).*$/\1/')

          if [[ -z $upload_url ]]; then
            echo "No upload URL found in response:" >&2
            echo "$response" >&2
            exit 1
          fi

          CURL_RESPONSE=$(curl --request POST \
              --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
              --header 'Content-Type: application/zip' \
              --url "${upload_url}?name=$RELEASE_FILENAME" \
              --data-binary "@$RELEASE_FILENAME" \
              --silent \
              --output - \
              --write-out "\n%{http_code}\n" )
          HTTP_CODE=$(echo $CURL_RESPONSE | tail -n 1)

          if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]]; then
            echo "Could not upload plugin archive $RELEASE_FILENAME to GitHub release:" >&2
            echo "$CURL_RESPONSE" | head -n -1 >&2
            exit 1
          fi

          echo "Assets uploaded."

      - name: Trigger translations update on GlotPress
        id: trigger_translations
        env:
          TAG: ${{ steps.get_tag.outputs.TAG_REF }}
          GLOTPRESS_IMPORT_URL: ${{ secrets.GLOTPRESS_IMPORT_URL }}
        shell: bash
        run: |
          echo "Triggering translations update on GlotPress..."

          CURL_RESPONSE=$(curl --request POST \
              --silent \
              --fail \
              --url "$GLOTPRESS_IMPORT_URL/$TAG")

          if [ $? -ne 0 ]; then
            echo "Could not trigger translations:"
            echo "$CURL_RESPONSE"
            exit 1
          fi

          echo "Translations update triggered."
