---
name: (pre-release) Weekly i18n tag
on:
    workflow_dispatch: []
    schedule:
        - cron: '0 20 * * 1'

jobs:
    weekly-18n-tag:
        name: Push i18n pre-release tag
        runs-on: ubuntu-20.04

        steps:
            # clone the repository
            - uses: actions/checkout@v2
              with:
                  ref: 'develop'

            - name: Push pre-release-tag
              run: |
                  TAG="i18n-$(date +%Y%m%d)-test"
                  MESSAGE="Version for internationalization testing $TAG."
                  MESSAGE+=" Not for production."

                  echo "Pushing tag '$TAG' to repository..."
                  git tag -a $TAG -m "$MESSAGE"
                  git push origin $TAG
