---
name: Release - Create PR
on:
  workflow_call:
    inputs:
      tagName:
        description: 'The tag name (e.g. 4.5.0)'
        required: true
        type: string
    outputs:
      branchName:
        description: "The branch created (e.g. release/4.5.0)"
        value: ${{ jobs.prepare-release.outputs.branch }}
  workflow_dispatch:
    inputs:
      tagName:
        description: 'The tag name (e.g. 4.5.0)'
        required: true
        type: string
      releaseDateString:
        description: "The release date in human-readable format, which will be formatted for changelog.txt and readme.txt (default: 'next wednesday')."
        required: false
        default: "next wednesday"
        type: string
  
defaults:
  run:
    shell: bash

jobs:
  prepare-release:
    name: Prepare a stable release with a Pull Request
    runs-on: ubuntu-20.04
    outputs: 
      branch: ${{ steps.create_branch_tag.outputs.BRANCH_NAME }}
    env:
      TAG_NAME: ${{ inputs.tagName }}
      RELEASE_DATE_STRING: ${{ inputs.releaseDateString }}    
    
    steps:
      - name: Checkout WCPay repository
        uses: actions/checkout@v3
#        with:
#          ref: 'develop'

      - name: Create a branch and tag
        id: create_branch_tag
        run: |
          BRANCH_NAME="release/$TAG_NAME"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"

          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          TAG_MESSAGE="Version $TAG_NAME"
          git tag -a -m "$TAG_MESSAGE" ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Setup Node and PHP with cache
        uses: ./.github/actions/setup-repo

      - name: Define variables
        id: define_var
        run: |
          RELEASE_DATE=$( date "+%Y-%m-%d" -d "$RELEASE_DATE_STRING" ) # Release date formatted as YYYY-MM-DD
          echo ::set-output name=RELEASE_DATE::"$RELEASE_DATE"
        
      - name: Generate the changelog
        id: generate_changelog
        uses: ./.github/actions/generate-changelog
        with:
          release-version: ${{ env.TAG_NAME }}
          release-date: ${{ steps.define_var.outputs.RELEASE_DATE }}
          
      - name: Bump version
        env:
          CHANGELOG: ${{ steps.generate_changelog.outputs.changelog }}
          RELEASE_DATE: ${{ steps.define_var.outputs.RELEASE_DATE }}
        run: |
          CURRENT_VERSION=$(jq '.version' package.json -r)

          # 'Version' header in woocommerce-payments.php
          sed -i "s/^ \* Version: .*$/ * Version: $TAG_NAME/" woocommerce-payments.php

          # 'version' field in package.json
          sed -ri 's/("version": )".*"/\1"'${TAG_NAME}'"/' package.json

          # 'Stable tag' header in readme.txt;
          sed -i "s/^Stable tag: .*$/Stable tag: $TAG_NAME/" readme.txt

          # Duplicate the generated changelog into the Changelog section from the readme.txt 
          sed -ri "s|(== Changelog ==)|\1\n\n= $TAG_NAME - $RELEASE_DATE =\n$CHANGELOG|" readme.txt
      
      - name: Build and commit changes
        env:
          BRANCH_NAME: ${{ steps.create_branch_tag.outputs.BRANCH_NAME }}
        run: |
          npm install
          git commit -am "Update version and add changelog entries for release $TAG_NAME"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create a PR to trunk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.generate_changelog.outputs.changelog }}
        run: |
          PR_BODY=$(echo -e "\`\`\`\n${CHANGELOG}\n\`\`\`")
          gh pr create --title "Release branch for $TAG_NAME" --body="$PR_BODY" --base="trunk"
