---
name: Release - Create PR
on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'The tag name (e.g. 4.5.0)'
        required: true
  
defaults:
  run:
    shell: bash

jobs:
  prepare-release:
    name: Prepare a stable release with a Pull Request
    runs-on: ubuntu-20.04
    outputs: 
      branch: ${{ steps.create_branch_tag.outputs.BRANCH_NAME }}
    env:
      TAG_NAME: ${{ inputs.tagName }}
      
    steps:
      - name: Checkout WCPay repository
        uses: actions/checkout@v3
#        with:
#          ref: 'develop'

#      - name: Create a branch and tag
#        id: create_branch_tag
#        run: |
#          BRANCH_NAME="release/$TAG_NAME"
#          TAG_MESSAGE="Version $TAG_NAME"
#          
#          git checkout -b $BRANCH_NAME
#          git push origin $BRANCH_NAME
#          echo "::set-output name=BRANCH_NAME::$(echo $BRANCH_NAME)"
#
#          git config user.name "${{ github.actor }}"
#          git config user.email "${{ github.actor }}@users.noreply.github.com"
          
#          git tag -a -m "$TAG_MESSAGE" ${{ env.TAG_NAME }}
#          echo "::set-output name=TAG_MESSAGE::$(echo $TAG_MESSAGE)"
#          
#          git push origin ${{ env.TAG_NAME }}

      - name: Setup Node and PHP with cache
        uses: ./.github/actions/setup-repo
        
      - name: Write changelog
        run: |
          # Install this dev package globally to gather changelog entries while not including it into the release package
          composer global require automattic/jetpack-changelogger:^3.0.7

          PLANNED_RELEASE_DATE=$( date "+%Y-%m-%d" -d "next wednesday") # Wednesday of current week as YYYY-MM-DD
          ~/.composer/vendor/bin/changelogger write --use-version="$TAG_NAME" --release-date="$PLANNED_RELEASE_DATE"
          
      - name: Extract changelog
        id: get_changelog
        run: |
          echo "Picking up changelog for version '$TAG_NAME'..."
          CHANGELOG=$(awk '/^= / { if (p) { exit }; p=1; next } p && NF' changelog.txt)
          echo "$CHANGELOG"
          
          sed -ri "s|(== Changelog ==)|\1\n\n $CHANGELOG|" readme.txt
          
          CHANGELOG_JSON_FORMATTED=$(echo "$CHANGELOG" | jq -aRs '.')
          echo "$CHANGELOG_JSON_FORMATTED"

          CHANGELOG_JSON_FORMATTED="${CHANGELOG_JSON_FORMATTED//'\n'/'%0A'}"  
          CHANGELOG_JSON_FORMATTED="${CHANGELOG_JSON_FORMATTED%\"}"
          CHANGELOG_JSON_FORMATTED="${CHANGELOG_JSON_FORMATTED#\"}"
          echo "$CHANGELOG_JSON_FORMATTED"
          echo ::set-output name=CHANGELOG_JSON::$(echo "$CHANGELOG")
          
      - name: Bump version
        env:
          CHANGELOG: ${{ steps.get_changelog.outputs.CHANGELOG_JSON }}
        run: |
          CURRENT_VERSION=$(jq '.version' package.json -r)

          # 'Version' header in woocommerce-payments.php
          sed -i "s/^ \* Version: .*$/ * Version: $TAG_NAME/" woocommerce-payments.php

          # 'version' field in package.json
          sed -ri 's/("version": )".*"/\1"'${TAG_NAME}'"/' package.json

          # 'Stable tag' header in readme.txt;
          sed -i "s/^Stable tag: .*$/Stable tag: $TAG_NAME/" readme.txt

          # Duplicate the changelog.txt content into the Changelog section in the readme.txt 
          sed -ri "s|(== Changelog ==)|\1\n\n $CHANGELOG|" readme.txt
      
#      - name: Build and commit changes
#        run: |
#          git commit -am "Add changelog entries for release $TAG_NAME"
#          git push --set-upstream origin release/$TAG_NAME
#
#      - name: Create a PR to trunk
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          CHANGELOG_JSON: ${{ steps.get_changelog.outputs.CHANGELOG_JSON }}
#        run: |
#          echo -e "\`\`\`${CHANGELOG_JSON}\`\`\`" > commitmsg
#          gh pr create --title "Release branch for $TAG_NAME" --body-file commitmsg --base="trunk"
